export let log = [
  {
    workoutID: 1,
    date: new Date("2024-10-02"),
    logEntryID: 1,
    name: "Workout A",
    type: "Resistance",
    excercises: [
      {
        name: "Squats",
        type: "Push",
        repetitions: 5,
        sets: 3,
        weight: 80,
        superset: false,
      },
      {
        name: "Bench press",
        type: "Push",
        repetitions: 5,
        sets: 3,
        weight: 60,
        superset: false
      },
      {
        name: "Pull-ups",
        type: "Pull",
        repetitions: 5,
        sets: 3,
        weight: "body",
        superset: false,
      },
      {
        name: "Bicep curls",
        type: "Pull",
        repetions: 8,
        sets: 3,
        weight: 30,
        superset: true,
      },
      {
        name: "Skull crushers",
        type: "Push",
        repetions: 8,
        sets: 3,
        weight: 30,
        superset: true,
      },
    ],
  },
  {
    workoutID: 2,
    date: new Date("2024-10-04"),
    logEntryID: 2,
    name: "Workout B",
    type: "Resistance",
    excercises: [
      {
        name: "Deadlifts",
        type: "Pull",
        repetitions: 5,
        sets: 3,
        weight: 90,
        superSet: false,
      },
      {
        name: "Military press",
        type: "Push",
        repetitions: 5,
        sets: 3,
        weight: 40,
        superSet: false,
      },
      {
        name: "Bent-over row",
        type: "Pull",
        repetitions: 5,
        sets: 3,
        weight: 50,
        superSet: false,
      },
      {
        name: "Hammer curls",
        type: "Pull",
        repetions: 8,
        sets: 3,
        weight: 16,
        superSet: true,
      },
      {
        name: "Tricep pushdown",
        type: "Push",
        repetions: 8,
        sets: 3,
        weight: 30,
        superSet: true,
      },
    ],
  },
  {
    workoutID: 1,
    date: new Date("2024-10-06"),
    logEntryID: 3,
    name: "Workout A",
    type: "Resistance",
    excercises: [
      {
        name: "Squats",
        type: "Push",
        repetitions: 5,
        sets: 3,
        superSet: false,
      },
      {
        name: "Bench press",
        type: "Push",
        repetitions: 5,
        sets: 3,
        superSet: false,
      },
      {
        name: "Pull-ups",
        type: "Pull",
        repetitions: 5,
        sets: 3,
        superSet: false,
      },
      {
        name: "Bicep curls",
        type: "Pull",
        repetions: 8,
        sets: 3,
        superSet: true,
      },
      {
        name: "Skull crushers",
        type: "Push",
        repetions: 8,
        sets: 3,
        superSet: true,
      },
    ],
  },
];